"use client"

import { ExternalLink, RotateCcw, Store } from "lucide-react"
import type { IngestResult } from "@/components/onboarding"
import { UcpExplorer } from "@/components/ucp-explorer"

// Generic fallback prompts only used if AI analysis fails AND the catalog has
// no real categories to ground a heuristic. Brand-specific prompts are
// generated at ingest time by `analyzeCatalog` in lib/analyze.ts.
const FALLBACK_PROMPTS = [
  "what categories do you carry?",
  "show me something under the median price",
  "I'm shopping for a gift",
  "compare two of your top picks",
  "help me style an outfit",
]

type Props = {
  store: IngestResult
  onReset: () => void
}

export function StoreRail({ store, onReset }: Props) {
  // Brand-specific prompts come from the AI analysis run at ingest time.
  const prompts =
    store.analysis?.prompts && store.analysis.prompts.length > 0
      ? store.analysis.prompts
      : FALLBACK_PROMPTS
  const tagline = store.analysis?.tagline?.trim()

  return (
    <aside className="flex h-full flex-col overflow-y-auto chat-scroll border-l border-border bg-background/40 p-5">
      {/* Store header */}
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg border border-border bg-card text-card-foreground">
            <Store className="h-5 w-5" />
          </div>
          <div className="min-w-0">
            <div className="truncate text-sm font-medium">{store.storeName}</div>
            <a
              href={store.storeUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1 truncate font-mono text-[11px] text-muted-foreground hover:text-primary"
            >
              {store.domain} <ExternalLink className="h-2.5 w-2.5" />
            </a>
          </div>
        </div>
        <button
          type="button"
          onClick={onReset}
          className="rounded-md border border-border p-1.5 text-muted-foreground transition-colors hover:border-primary/40 hover:text-foreground"
          aria-label="Disconnect store"
          title="Disconnect"
        >
          <RotateCcw className="h-3.5 w-3.5" />
        </button>
      </div>

      {/* AI brand read: tagline + origin pill + positioning + price tier.
          All values are produced by lib/analyze.ts at ingest time, grounded
          in the real catalog (titles, categories, currency). */}
      {store.analysis ? (
        <div className="mt-3 rounded-lg border border-primary/30 bg-primary/5 p-3">
          <div className="mb-1.5 flex items-center gap-2">
            <span className="font-mono text-[9px] uppercase tracking-widest text-primary/80">
              AI brand read
            </span>
            {store.analysis.brand?.origin ? (
              <span className="rounded-full border border-primary/30 px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-wider text-primary">
                {store.analysis.brand.origin}
              </span>
            ) : null}
          </div>
          {tagline ? (
            <p className="text-xs font-medium leading-relaxed text-foreground/95">
              {tagline}
            </p>
          ) : null}
          {store.analysis.brand?.positioning ? (
            <p className="mt-1 text-[11px] leading-relaxed text-foreground/70">
              {store.analysis.brand.positioning}
            </p>
          ) : null}
          {store.analysis.brand?.price_tier ? (
            <div className="mt-2 font-mono text-[10px] text-muted-foreground">
              {store.analysis.brand.price_tier}
            </div>
          ) : null}
        </div>
      ) : null}

      <div className="mt-4 grid grid-cols-2 gap-2">
        <Stat label="Products" value={store.productCount.toLocaleString()} />
        <Stat label="Currency" value={store.currency} />
      </div>

      {/* Capabilities */}
      <div className="mt-5">
        <div className="mb-2 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
          UCP Capabilities
        </div>
        <div className="flex flex-wrap gap-1.5">
          {store.capabilities.map((c) => (
            <span
              key={c}
              className="rounded-md bg-accent px-2 py-0.5 font-mono text-[10px] uppercase tracking-wider text-accent-foreground"
            >
              {c}
            </span>
          ))}
        </div>
      </div>

      {/* Brand-specific suggested prompts (generated by the AI analysis layer) */}
      <div className="mt-6">
        <div className="mb-2 flex items-center justify-between">
          <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
            Try a prompt
          </span>
          {store.analysis ? (
            <span className="rounded-full bg-primary/10 px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-wider text-primary">
              ai-tailored
            </span>
          ) : null}
        </div>
        <div className="flex flex-col gap-1.5">
          {prompts.map((p) => (
            <button
              key={p}
              type="button"
              onClick={() => {
                // Dispatch a custom event the chat panel can hook into.
                window.dispatchEvent(
                  new CustomEvent("ai-shelf:sample-prompt", { detail: p }),
                )
              }}
              className="text-left rounded-md border border-border bg-secondary/40 px-3 py-2 text-xs text-foreground/80 transition-colors hover:border-primary/40 hover:text-foreground"
            >
              {p}
            </button>
          ))}
        </div>
      </div>

      {/* Discount codes hint */}
      <div className="mt-6 rounded-lg border border-border bg-card/40 p-3">
        <div className="mb-1.5 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
          Demo discount codes
        </div>
        <ul className="space-y-1 font-mono text-[11px] text-card-foreground/90">
          <li>
            <span className="text-primary">WELCOME10</span> · 10% off
          </li>
          <li>
            <span className="text-primary">FLAT500</span> · flat off
          </li>
          <li>
            <span className="text-primary">FREESHIP</span> · free shipping
          </li>
        </ul>
      </div>

      {/* UCP Explorer — every published endpoint, not just the manifest. */}
      <div className="mt-6">
        <div className="mb-2 flex items-center justify-between">
          <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
            UCP Endpoints
          </span>
          <span className="rounded-full bg-primary/10 px-1.5 py-0.5 font-mono text-[9px] uppercase tracking-wider text-primary">
            live
          </span>
        </div>
        <UcpExplorer store={store} />
      </div>
    </aside>
  )
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-border bg-card/40 px-3 py-2">
      <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
        {label}
      </div>
      <div className="mt-0.5 text-sm font-medium text-foreground">{value}</div>
    </div>
  )
}
